name: 'goat_pipeline'
version: '1.0.0'
config-version: 2
profile: 'goat_pipeline'

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  goat_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
